### ISSUE TITLE
Can't Install RailsOneClick

### ISSUE THREAD

**Issue by dawie** [oscardelben/RailsOneClick#2]
I have Xcode 4.3.2 installed (via the Mac App Store). I am currently on Mac OS X 10.7.3.

When I check the Prerequisites I get the following message:

Before developing on Mac os X you need to download a free copy of the "Command Line Tools for Xcode" package from https://developer.apple.com/downloads - In alternative you can download a copy of Xcode from the AppStore.

When I click on Begin Installation, I get the same error message.

It does not make sense to me, since I have all the Prerequisites installed.

**Comment by oscardelben** [comment]
Thanks, I will look into it and update you.

**Comment by oscardelben** [comment]
Hi, could you check if you have make installed in your system? That's what I use to check for right now.

**Comment by modocache** [comment]
RailsOneClick checks for the presence of `make` when [checking for prerequisites](https://github.com/oscardelben/RailsOneClick/blob/master/RailsOneClick/InstallViewController.m#L50). It's possible that `make` is not on your PATH. The problem (and a solution) can be found here: http://stackoverflow.com/a/10217910/679254

**Comment by dawie** [comment]
I added the following to my .bash_profile file:
export PATH=$PATH:/Applications/Xcode.app/Contents/Developer/usr/bin
export PATH=$PATH:/Applications/Xcode.app/Contents/Developer/Tools

I reloaded the profile.

When I run "make" I get:
make: **\* No targets specified and no makefile found.  Stop.

RailsOnClick still gives me the same errors though.

On Thu, May 10, 2012 at 9:42 PM, modocache <
reply@reply.github.com

**Comment by oscardelben** [comment]
I'm working on a fix right now, which will be available as an update, thanks a lot for reporting the issue!

**Comment by oscardelben** [comment]
It tuns out that this issue can't be solved easily, in particular it's impossible for me to read the user's path, and thus make this work.

I'm going to change the install instructions for now and recommend downloading Apple's build tools.

@dawie I'm sorry for the trouble, but it looks like installing Xcode's command line tools is the best (and supported) way to go through this. If you go to Xcode preferences -> downloads, you'll be able to install the tools from there.

I'm closing this for now, but if you run into other issues let me know.
