### ISSUE TITLE
configure: error: in `/tmp/yaml-0.1.4

### ISSUE THREAD

**Issue by LukeMichaels** [oscardelben/RailsOneClick#20]
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/yaml-0.1.4':
configure: error: C compiler cannot create executables
See`config.log' for more details

**Comment by Paintsius** [comment]
i uninstalled Xcode then had r1c install it

**Comment by oscardelben** [comment]
Hi, if you are using Maverick then Rails One Click is no longer needed. Just go into a terminal and type:

`gem install rails`

**Comment by LukeMichaels** [comment]
Thanks guys
